// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEnNP-vznzi9SPzYIiqebZNqpwjx79PJs',
    appId: '1:883271663429:web:23809f5b0c6af9e07d482c',
    messagingSenderId: '883271663429',
    projectId: 'flutter-stylish-webrtc',
    authDomain: 'flutter-stylish-webrtc.firebaseapp.com',
    databaseURL: 'https://flutter-stylish-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-stylish-webrtc.appspot.com',
    measurementId: 'G-Y5J6T7CWVL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqZnGIOOiQUUQZJSUSwEyBnU7zcajgJiM',
    appId: '1:883271663429:android:f9b8aea7f05170727d482c',
    messagingSenderId: '883271663429',
    projectId: 'flutter-stylish-webrtc',
    databaseURL: 'https://flutter-stylish-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-stylish-webrtc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjIuZi8Wk1UWBOn5TQYrApKdBAV-Csnc',
    appId: '1:883271663429:ios:0feead69a96c66917d482c',
    messagingSenderId: '883271663429',
    projectId: 'flutter-stylish-webrtc',
    databaseURL: 'https://flutter-stylish-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-stylish-webrtc.appspot.com',
    iosClientId: '883271663429-mouijlmm7n6n4apfl2kjme0d8omnukra.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMinjingStylish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjIuZi8Wk1UWBOn5TQYrApKdBAV-Csnc',
    appId: '1:883271663429:ios:214c21f6991dee917d482c',
    messagingSenderId: '883271663429',
    projectId: 'flutter-stylish-webrtc',
    databaseURL: 'https://flutter-stylish-webrtc-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'flutter-stylish-webrtc.appspot.com',
    iosClientId: '883271663429-8p10ds04tc5o88q18o8ab0ctckdo86ac.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterMinjingStylish.RunnerTests',
  );
}
